/** Row shape for `public.public_market_listings` (snake_case, matches Supabase). */
export type PublicMarketListingRow = {
  id: string;
  tenant_id: string;
  vendor_id: string;
  branch_id: string;
  storefront_id: string;
  product_id: string;
  sku: string | null;
  listing_slug: string;
  title: string;
  short_description: string | null;
  brand: string | null;
  category_id: string | null;
  category_name: string | null;
  searchable_text: string | null;
  public_price: number;
  compare_at_price: number | null;
  currency_code: string;
  stock_badge: string | null;
  stock_signal: string | null;
  hero_image_url: string | null;
  image_count: number;
  verification_flag: boolean;
  trust_score: number | null;
  freshness_score: number | null;
  ranking_score: number | null;
  publish_status: string;
  city: string | null;
  suburb: string | null;
  province: string | null;
  country: string | null;
  lat: number | null;
  lng: number | null;
  radius_km: number | null;
  same_city_priority: boolean;
  same_suburb_priority: boolean;
  cross_border_allowed: boolean;
  pickup_supported: boolean;
  delivery_supported: boolean;
  visible_in_market_space: boolean;
  visible_in_itred: boolean;
  published_at: string | null;
  refreshed_at: string;
};

export type PublicVendorRow = {
  id: string;
  tenant_id: string;
  vendor_id: string;
  business_name: string;
  public_slug: string;
  logo_url: string | null;
  hero_image_url: string | null;
  short_description: string | null;
  verified_badge: boolean;
  trust_score: number | null;
  primary_category: string | null;
  country: string | null;
  province: string | null;
  city: string | null;
  suburb: string | null;
  storefront_id: string;
  storefront_slug: string;
  active: boolean;
  published_at: string | null;
  updated_at: string;
};

export type PublicStorefrontRow = {
  id: string;
  tenant_id: string;
  vendor_id: string;
  storefront_id: string;
  storefront_slug: string;
  storefront_title: string;
  primary_branch_id: string | null;
  default_country: string | null;
  default_city: string | null;
  public_status: string;
  contact_whatsapp: string | null;
  contact_phone: string | null;
  pickup_enabled: boolean;
  delivery_enabled: boolean;
  active: boolean;
  updated_at: string;
};
