import type { SectorConfig } from "../types/sector";

/**
 * Canonical sector definitions (mirrored in Supabase `product_sectors.field_definitions`).
 * Prefer {@link import("./sector-registry").listSectorDefinitions} for app-wide reads.
 */
export const SECTORS: SectorConfig[] = [
  {
    id: "motor_spares",
    label: "Motor spares",
    fields: [
      { key: "vehicleMake", label: "Vehicle make", type: "text", placeholder: "e.g. Toyota" },
      { key: "vehicleModel", label: "Vehicle model", type: "text", placeholder: "e.g. Hilux" },
      { key: "engineNumber", label: "Engine number", type: "text", placeholder: "If applicable" },
      { key: "year", label: "Year", type: "number", placeholder: "e.g. 2016", min: 1900, step: "1" },
      { key: "partNumber", label: "Part number", type: "text", required: true },
      { key: "compatibilityNotes", label: "Compatibility notes", type: "text" },
    ],
  },
  {
    id: "motor_vehicle",
    label: "Motor vehicles",
    fields: [
      { key: "vehicleType", label: "Vehicle type", type: "select", required: true, options: [
        { value: "sedan", label: "Sedan" },
        { value: "suv", label: "SUV" },
        { value: "truck", label: "Truck" },
        { value: "bus", label: "Bus" },
        { value: "tractor", label: "Tractor" },
        { value: "motorcycle", label: "Motorcycle" },
        { value: "other", label: "Other" },
      ]},
      { key: "make", label: "Make", type: "text", required: true, placeholder: "e.g. Toyota" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "e.g. Hilux" },
      { key: "variant", label: "Variant / trim", type: "text", placeholder: "e.g. 2.8 GD-6" },
      { key: "year", label: "Year of manufacture", type: "number", required: true, min: 1900, step: "1", placeholder: "e.g. 2018" },
      { key: "condition", label: "Condition", type: "select", required: true, options: [
        { value: "new", label: "New" },
        { value: "used", label: "Used" },
        { value: "reconditioned", label: "Reconditioned" },
      ]},
      { key: "fuelType", label: "Fuel type", type: "select", required: true, options: [
        { value: "petrol", label: "Petrol" },
        { value: "diesel", label: "Diesel" },
        { value: "hybrid", label: "Hybrid" },
        { value: "electric", label: "Electric" },
        { value: "other", label: "Other" },
      ]},
      { key: "transmission", label: "Transmission", type: "select", required: true, options: [
        { value: "manual", label: "Manual" },
        { value: "automatic", label: "Automatic" },
        { value: "cvt", label: "CVT" },
        { value: "other", label: "Other" },
      ]},
      { key: "engineCapacity", label: "Engine capacity", type: "text", placeholder: "e.g. 2.8L" },
      { key: "mileage", label: "Mileage", type: "number", min: 0, step: "1", placeholder: "e.g. 125000" },
      { key: "color", label: "Color", type: "text" },
      { key: "vin", label: "VIN / chassis number (internal)", type: "text", helpText: "Keep internal unless you choose to publish it." },
      { key: "engineNumber", label: "Engine number (internal)", type: "text" },
      { key: "registrationNumber", label: "Registration number", type: "text" },
      { key: "documentStatus", label: "Ownership document status", type: "select", required: true, options: [
        { value: "available", label: "Available" },
        { value: "pending", label: "Pending" },
        { value: "missing", label: "Missing" },
      ]},
      { key: "features", label: "Features / options", type: "textarea", rows: 4, fullWidth: true, placeholder: "e.g. Aircon, reverse camera, Bluetooth" },
    ],
  },
  {
    id: "property",
    label: "Property",
    fields: [
      { key: "propertyType", label: "Property type", type: "select", required: true, options: [
        { value: "house", label: "House" },
        { value: "flat", label: "Flat" },
        { value: "apartment", label: "Apartment" },
        { value: "commercial_shop", label: "Commercial shop" },
        { value: "office", label: "Office" },
        { value: "stand", label: "Stand" },
        { value: "warehouse", label: "Warehouse" },
        { value: "farm", label: "Farm" },
        { value: "lodge", label: "Lodge" },
        { value: "other", label: "Other" },
      ]},
      { key: "offerType", label: "Offer type", type: "select", required: true, options: [
        { value: "for_sale", label: "For sale" },
        { value: "to_rent", label: "To rent" },
        { value: "short_stay", label: "Short stay" },
        { value: "lease", label: "Lease" },
      ]},
      { key: "address", label: "Physical address", type: "text", required: true, placeholder: "Street / area" },
      { key: "country", label: "Country", type: "text", required: true },
      { key: "province", label: "Province / state", type: "text" },
      { key: "city", label: "City / town", type: "text", required: true },
      { key: "suburb", label: "Suburb / area", type: "text" },
      { key: "geo", label: "Geo coordinates", type: "text", placeholder: "e.g. -17.8292, 31.0522" },
      { key: "bedrooms", label: "Bedrooms", type: "number", min: 0, step: "1", required: true },
      { key: "bathrooms", label: "Bathrooms", type: "number", min: 0, step: "1", required: true },
      { key: "condition", label: "Condition", type: "select", required: true, options: [
        { value: "new", label: "New" },
        { value: "good", label: "Good" },
        { value: "needs_work", label: "Needs work" },
        { value: "under_renovation", label: "Under renovation" },
      ]},
      { key: "occupancy", label: "Occupancy status", type: "select", required: true, options: [
        { value: "vacant", label: "Vacant" },
        { value: "occupied", label: "Occupied" },
        { value: "under_renovation", label: "Under renovation" },
      ]},
      { key: "billingCycle", label: "Billing cycle", type: "select", required: true, options: [
        { value: "once_off", label: "Once-off" },
        { value: "daily", label: "Daily" },
        { value: "weekly", label: "Weekly" },
        { value: "monthly", label: "Monthly" },
        { value: "annual", label: "Annual" },
      ]},
      { key: "availabilityDate", label: "Availability date", type: "date" },
      { key: "utilities", label: "Utilities available", type: "textarea", rows: 3, fullWidth: true, placeholder: "e.g. Water, solar, borehole, Wi‑Fi" },
    ],
  },
  {
    id: "clothing",
    label: "Clothing",
    fields: [
      { key: "size", label: "Size", type: "select", options: [{ value: "XS", label: "XS" }, { value: "S", label: "S" }, { value: "M", label: "M" }, { value: "L", label: "L" }, { value: "XL", label: "XL" }, { value: "XXL", label: "XXL" }] },
      { key: "color", label: "Color", type: "text" },
      { key: "material", label: "Material", type: "text" },
      { key: "gender", label: "Gender", type: "select", options: [{ value: "unisex", label: "Unisex" }, { value: "mens", label: "Men's" }, { value: "womens", label: "Women's" }, { value: "kids", label: "Kids" }] },
    ],
  },
  {
    id: "pharmacy",
    label: "Pharmacy",
    fields: [
      { key: "dosageForm", label: "Dosage form", type: "select", options: [{ value: "tablet", label: "Tablet" }, { value: "capsule", label: "Capsule" }, { value: "syrup", label: "Syrup" }, { value: "ointment", label: "Ointment" }, { value: "injection", label: "Injection" }, { value: "other", label: "Other" }] },
      { key: "strength", label: "Strength", type: "text", placeholder: "e.g. 500mg" },
      { key: "requiresPrescription", label: "Requires prescription", type: "boolean" },
      { key: "activeIngredient", label: "Active ingredient", type: "text" },
    ],
  },
  {
    id: "grocery",
    label: "Grocery",
    fields: [
      { key: "expiryDays", label: "Expiry (days)", type: "number", placeholder: "e.g. 30" },
      { key: "perishable", label: "Perishable", type: "boolean" },
      { key: "originCountry", label: "Origin country", type: "text" },
    ],
  },
  {
    id: "hardware",
    label: "Hardware",
    fields: [
      { key: "spec", label: "Specification / grade", type: "text", placeholder: "e.g. 10mm, galvanized" },
      { key: "materialType", label: "Material type", type: "text", placeholder: "e.g. Steel, PVC, Timber" },
      { key: "dimensions", label: "Size / dimensions", type: "text", placeholder: "e.g. 2m x 1m x 12mm" },
      { key: "warrantyMonths", label: "Warranty (months)", type: "number" },
      { key: "powerRating", label: "Power rating", type: "text", placeholder: "e.g. 500W" },
    ],
  },
  {
    id: "leisure_resort",
    label: "Leisure & resort",
    fields: [
      { key: "serviceType", label: "Service type", type: "select", required: true, options: [
        { value: "day_visit", label: "Day visit" },
        { value: "event_package", label: "Event package" },
        { value: "accommodation", label: "Accommodation" },
        { value: "activity", label: "Activity" },
        { value: "venue_hire", label: "Venue hire" },
        { value: "membership", label: "Membership" },
        { value: "other", label: "Other" },
      ]},
      { key: "siteLocation", label: "Resort / site location", type: "text", required: true },
      { key: "facilityName", label: "Facility / venue name", type: "text" },
      { key: "capacity", label: "Capacity", type: "number", min: 0, step: "1", required: true },
      { key: "bookingRequired", label: "Booking required", type: "boolean" },
      { key: "bookingUnit", label: "Booking unit", type: "select", required: true, options: [
        { value: "per_person", label: "Per person" },
        { value: "per_room", label: "Per room" },
        { value: "per_group", label: "Per group" },
        { value: "per_hour", label: "Per hour" },
        { value: "per_day", label: "Per day" },
      ]},
      { key: "operatingDays", label: "Operating days", type: "text", placeholder: "e.g. Mon–Sun" },
      { key: "openingTime", label: "Opening time", type: "text", placeholder: "e.g. 08:00" },
      { key: "closingTime", label: "Closing time", type: "text", placeholder: "e.g. 17:00" },
      { key: "cancellationRule", label: "Cancellation rule", type: "textarea", rows: 3, fullWidth: true },
      { key: "safetyRules", label: "Safety / usage rules", type: "textarea", rows: 3, fullWidth: true },
    ],
  },
  {
    id: "hotel",
    label: "Hotel",
    fields: [
      { key: "roomType", label: "Room type", type: "select", required: true, options: [
        { value: "standard", label: "Standard" },
        { value: "deluxe", label: "Deluxe" },
        { value: "twin", label: "Twin" },
        { value: "family", label: "Family" },
        { value: "executive_suite", label: "Executive suite" },
        { value: "other", label: "Other" },
      ]},
      { key: "capacity", label: "Capacity", type: "number", required: true, min: 1, step: "1" },
      { key: "beds", label: "Number of beds", type: "number", required: true, min: 0, step: "1" },
      { key: "bedType", label: "Bed type", type: "text", placeholder: "e.g. Queen, Twin" },
      { key: "rateType", label: "Rate type", type: "select", required: true, options: [
        { value: "room_only", label: "Room only" },
        { value: "bed_breakfast", label: "Bed & breakfast" },
        { value: "half_board", label: "Half board" },
        { value: "full_board", label: "Full board" },
      ]},
      { key: "checkInTime", label: "Check-in time", type: "text", required: true, placeholder: "e.g. 14:00" },
      { key: "checkOutTime", label: "Check-out time", type: "text", required: true, placeholder: "e.g. 10:00" },
      { key: "amenities", label: "Amenities", type: "textarea", rows: 4, fullWidth: true, placeholder: "e.g. Wi‑Fi, aircon, breakfast" },
      { key: "cancellationPolicy", label: "Cancellation policy", type: "textarea", rows: 3, fullWidth: true },
      { key: "minimumStay", label: "Minimum stay (nights)", type: "number", min: 1, step: "1" },
    ],
  },
  {
    id: "confectionery",
    label: "Confectionery",
    fields: [
      { key: "flavor", label: "Flavor / variant", type: "text", required: true },
      { key: "netWeight", label: "Net weight / volume", type: "text", required: true, placeholder: "e.g. 100g, 330ml" },
      { key: "packSize", label: "Pack size", type: "text", required: true, placeholder: "e.g. 24 x 330ml" },
      { key: "packagingType", label: "Packaging type", type: "select", required: true, options: [
        { value: "packet", label: "Packet" },
        { value: "box", label: "Box" },
        { value: "bottle", label: "Bottle" },
        { value: "jar", label: "Jar" },
        { value: "wrapper", label: "Wrapper" },
        { value: "tray", label: "Tray" },
        { value: "other", label: "Other" },
      ]},
      { key: "batchNumber", label: "Batch number (if applicable)", type: "text" },
      { key: "manufactureDate", label: "Manufacture date", type: "date" },
      { key: "expiryDate", label: "Expiry / best before", type: "date" },
      { key: "storageCondition", label: "Storage condition", type: "select", required: true, options: [
        { value: "ambient", label: "Ambient" },
        { value: "cool_dry", label: "Cool & dry" },
        { value: "refrigerated", label: "Refrigerated" },
        { value: "frozen", label: "Frozen" },
      ]},
      { key: "allergens", label: "Allergen information", type: "textarea", rows: 3, fullWidth: true },
    ],
  },
  {
    id: "electronics",
    label: "Electronics",
    fields: [
      { key: "modelNumber", label: "Model number", type: "text" },
      { key: "warrantyMonths", label: "Warranty (months)", type: "number" },
      { key: "voltage", label: "Voltage", type: "text", placeholder: "e.g. 220V" },
    ],
  },
  {
    id: "agriculture",
    label: "Agriculture",
    fields: [
      {
        key: "agriProductType",
        label: "Product type",
        type: "select",
        required: true,
        helpText: "Livestock, grains, or horticulture — drives how buyers filter this listing.",
        options: [
          { value: "livestock", label: "Livestock" },
          { value: "grains", label: "Grains" },
          { value: "horticulture", label: "Horticulture" },
        ],
      },
      {
        key: "cropOrProduct",
        label: "Crop / product name",
        type: "text",
        required: true,
        placeholder: "e.g. Maize, beef weaners, baby marrows",
        helpText: "Searchable name for this line (what you are selling).",
      },
      {
        key: "varietyOrBreed",
        label: "Variety or breed",
        type: "text",
        placeholder: "e.g. PAN 14, Angus, Roma tomato",
      },
      {
        key: "harvestDate",
        label: "Harvest / ready date",
        type: "date",
        helpText: "Expected harvest, slaughter-ready, or pack date for fresh produce.",
      },
      {
        key: "packaging",
        label: "Packaging",
        type: "select",
        options: [
          { value: "bulk", label: "Bulk" },
          { value: "bags", label: "Bags" },
          { value: "crates", label: "Crates" },
          { value: "punnets", label: "Punnets" },
          { value: "bales", label: "Bales" },
          { value: "other", label: "Other" },
        ],
      },
      {
        key: "packagingDetail",
        label: "Packaging detail",
        type: "text",
        placeholder: "e.g. 25kg bags, 4×4 kg punnets",
      },
      {
        key: "season",
        label: "Season",
        type: "select",
        options: [
          { value: "all", label: "All-year" },
          { value: "rainy", label: "Rainy" },
          { value: "dry", label: "Dry" },
        ],
      },
      {
        key: "pricePerUnitOffer",
        label: "Offer price per unit",
        type: "number",
        placeholder: "e.g. 12.50",
        step: "0.01",
        min: 0,
        helpText: "Asking price for this listing (sale lead). Main catalog price above should match or reflect your floor.",
      },
      {
        key: "unitForOffer",
        label: "Unit for offer",
        type: "select",
        options: [
          { value: "kg", label: "kg" },
          { value: "ton", label: "ton" },
          { value: "bag", label: "bag" },
          { value: "crate", label: "crate" },
          { value: "head", label: "head" },
          { value: "dozen", label: "dozen" },
          { value: "each", label: "each" },
        ],
      },
      {
        key: "organicCertified",
        label: "Certified organic",
        type: "boolean",
      },
      {
        key: "saleLeadNotes",
        label: "Sale lead details",
        type: "textarea",
        fullWidth: true,
        rows: 5,
        placeholder:
          "MOQ, delivery radius, cold chain, grading, certifications, payment terms — anything that turns a browser into a buyer.",
        helpText: "Shown in search text and helps staff qualify leads.",
      },
    ],
  },
  {
    id: "cosmetics",
    label: "Cosmetics",
    fields: [
      { key: "skinType", label: "Skin type", type: "select", options: [{ value: "all", label: "All" }, { value: "oily", label: "Oily" }, { value: "dry", label: "Dry" }, { value: "sensitive", label: "Sensitive" }] },
      { key: "shade", label: "Shade", type: "text" },
      { key: "fragranceFree", label: "Fragrance-free", type: "boolean" },
    ],
  },
  {
    id: "stationery",
    label: "Stationery",
    fields: [
      { key: "paperSize", label: "Paper size", type: "select", options: [{ value: "A4", label: "A4" }, { value: "A5", label: "A5" }, { value: "A3", label: "A3" }, { value: "letter", label: "Letter" }] },
      { key: "pages", label: "Pages", type: "number" },
      { key: "binding", label: "Binding", type: "select", options: [{ value: "spiral", label: "Spiral" }, { value: "glued", label: "Glued" }, { value: "stitched", label: "Stitched" }, { value: "none", label: "None" }] },
    ],
  },
  {
    id: "general_merchandise",
    label: "General merchandise",
    fields: [{ key: "notes", label: "Sector notes", type: "text", placeholder: "Any extra details" }],
  },
];

export function getSectorConfig(sectorId: string) {
  return SECTORS.find((s) => s.id === sectorId);
}
